-- Migration: Add is_default column and seed default industry categories
ALTER TABLE "public"."category" ADD COLUMN IF NOT EXISTS "is_default" BOOLEAN NOT NULL DEFAULT false;

-- Default categories for general (store: default_store_1)
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('6b12eb26-ed71-5764-d311-13259f060c18', 'general', 'default_store_1', 'Daily Essentials', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('3c3a4365-f59f-7ea4-3ac3-2665b6abb4b9', 'general', 'default_store_1', 'Beverages & Drinks', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('b259e56d-6c01-6c17-3d7e-1963811c4b19', 'general', 'default_store_1', 'Snacks & Packaged Food', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('19c4fa4b-d0c5-2319-1b95-e45758cdbba6', 'general', 'default_store_1', 'Personal Care & Hygiene', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('47776c71-129c-fe32-e8e1-6f2571666252', 'general', 'default_store_1', 'Cleaning & Household', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('bfe4c355-42f5-df6b-a8fc-a969c79d05bf', 'general', 'default_store_1', 'Stationery & Paper', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('20e447d9-1897-73fb-b31f-0427ea656e34', 'general', 'default_store_1', 'Dairy Products', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('2de7c01e-dbd5-97d7-93e9-d9894d52d89e', 'general', 'default_store_1', 'Miscellaneous', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;

-- Default categories for medical (store: default_store_2)
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('6a6ac0c4-915f-65ad-28bf-4a253054e04b', 'medical', 'default_store_2', 'Prescription Medicines', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('f1b4821b-4b00-985e-13a9-42c2a8156d33', 'medical', 'default_store_2', 'OTC & Health Supplements', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('d7a0fe33-8caa-85c7-fe6d-c82e7678f88d', 'medical', 'default_store_2', 'First Aid & Surgical', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('42bc360b-06d4-c3d0-90f2-ed802bc035fe', 'medical', 'default_store_2', 'Personal Hygiene & Sanitization', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('26bd847a-1115-461b-9847-fdf5b8d18c48', 'medical', 'default_store_2', 'Baby & Mother Care', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('e33eb21e-a3b9-8b3c-056f-63f133193e9a', 'medical', 'default_store_2', 'Medical Equipment & Devices', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('d5448e88-a76f-0829-6a48-953609e7cb97', 'medical', 'default_store_2', 'Ayurvedic & Herbal', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;

-- Default categories for grocery (store: default_store_3)
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('57eb9589-93fd-d5a5-e1dd-3f7f97ca80cf', 'grocery', 'default_store_3', 'Daily Essentials', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('41b82402-807a-d6e9-aaf5-c7f85074f9df', 'grocery', 'default_store_3', 'Staples, Grains & Flours', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('bf7bd95f-b6fe-9de6-aff8-ae6c3e62ca9b', 'grocery', 'default_store_3', 'Pulses & Dals', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('a3f74c18-eead-5a96-62db-f6fafdbc5bb9', 'grocery', 'default_store_3', 'Edible Oils & Ghee', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('ea3377bc-efcf-66e6-3ec3-b4aae4fe1c42', 'grocery', 'default_store_3', 'Spices, Masalas & Seasonings', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('19035fc2-878a-2fed-a438-7e271e3dca6d', 'grocery', 'default_store_3', 'Snacks, Biscuits & Namkeen', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('5b6a1c93-c9c0-fdbf-8833-84a62c47db06', 'grocery', 'default_store_3', 'Beverages & Cold Drinks', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('90250ccf-b69b-339d-b676-2f69a21cddfd', 'grocery', 'default_store_3', 'Cleaning & Detergents', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('c47d0b4b-2740-dc87-34f9-05d4e2160585', 'grocery', 'default_store_3', 'Personal Care & Soaps', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('d9e13c59-0c8e-6b8d-c23b-33c1e0a258b0', 'grocery', 'default_store_3', 'Dairy, Butter & Eggs', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;

-- Default categories for dairy_sweets (store: default_store_4)
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('db508c1c-84c0-f386-eaa0-d9b80ea70034', 'dairy_sweets', 'default_store_4', 'Fresh Milk & Buttermilk', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('cd14b8ec-c956-9172-200b-03f3f2ec62dc', 'dairy_sweets', 'default_store_4', 'Curd, Paneer & Cheese', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('97950400-9c83-dce9-a4c6-46179575694c', 'dairy_sweets', 'default_store_4', 'Pure Ghee & Butter', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('f034369d-988f-f456-63c7-92b63c083208', 'dairy_sweets', 'default_store_4', 'Traditional Sweets (Mithai)', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('422afd12-6e68-e86a-be04-b1aaf60d1927', 'dairy_sweets', 'default_store_4', 'Bengali & Milk Sweets', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('4ad6c53c-1a12-00b7-382d-18a8e74a69f5', 'dairy_sweets', 'default_store_4', 'Ice Cream, Kulfi & Desserts', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('5eabca2a-b28a-9f0e-7989-a9610341815d', 'dairy_sweets', 'default_store_4', 'Dry Fruit Sweets', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('735e6acf-dd8b-3abc-e9bf-7cfa028b3f17', 'dairy_sweets', 'default_store_4', 'Namkeen & Farsan', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;

-- Default categories for bakery (store: default_store_5)
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('67fd5f83-ca86-dae3-ada3-b38a68bb6d5d', 'bakery', 'default_store_5', 'Fresh Breads & Pav', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('ff338d79-853d-b3ab-760a-c2376a73cff4', 'bakery', 'default_store_5', 'Cakes, Pastries & Muffins', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('10da4e1f-78ab-20e2-881f-5447749907e5', 'bakery', 'default_store_5', 'Cookies, Rusk & Biscuits', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('3e7ec85a-963b-5243-f18f-989f4bff30d8', 'bakery', 'default_store_5', 'Savory Bakes & Puffs', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('9f73b46e-b56f-161b-a8b2-a4e1d0646b5c', 'bakery', 'default_store_5', 'Chocolates & Candies', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('ad0905f0-4827-b137-b5c8-e5c5f82945ac', 'bakery', 'default_store_5', 'Baking Ingredients & Pre-mixes', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;

-- Default categories for footwear (store: default_store_6)
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('f5bda931-1d1d-81e1-113a-ceeb1529f857', 'footwear', 'default_store_6', 'Men''s Formal & Casual Shoes', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('6b1b95ca-dc37-74de-945e-0b89723cf9c8', 'footwear', 'default_store_6', 'Women''s Shoes & Heels', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('682dea48-6eb2-9dde-6b27-8777ebda1d40', 'footwear', 'default_store_6', 'Kids'' Footwear & School Shoes', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('14365392-fde8-4aed-2a8f-4b056631b8e6', 'footwear', 'default_store_6', 'Sports & Running Shoes', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('04192b78-fcee-311a-9c6c-0261c4ddc6e4', 'footwear', 'default_store_6', 'Sandals, Slippers & Flip-Flops', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('b9d5d79c-e73b-e327-ce31-f4df14653abb', 'footwear', 'default_store_6', 'Socks & Shoe Care Accessories', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;

-- Default categories for electronics (store: default_store_7)
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('f1d0d184-59f6-5238-ec2c-b824c26d63d4', 'electronics', 'default_store_7', 'Mobile Phones & Tablets', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('2e50baa1-3a4f-eb79-8544-b46a4e56830c', 'electronics', 'default_store_7', 'Earphones, Headphones & Audio', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('0e9ad294-638b-b8b3-73d9-ecb3e802631f', 'electronics', 'default_store_7', 'Chargers, Cables & Power Banks', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('ddd2e8d6-56ec-1d1b-8991-151bb89a7689', 'electronics', 'default_store_7', 'Mobile Cases & Screen Guards', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('2c8f223a-a9fd-caa1-6a14-0fdaf27846c2', 'electronics', 'default_store_7', 'Computer & Laptop Peripherals', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('0d48d8b9-fa37-8c03-1ac5-01b760a26fb9', 'electronics', 'default_store_7', 'Smart Watches & Wearables', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('42dbe680-fd9b-a290-c17e-1227059dc4f5', 'electronics', 'default_store_7', 'Small Home Appliances', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;

-- Default categories for hardware (store: default_store_8)
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('54428743-f9ca-7f75-70e9-5e252a940a97', 'hardware', 'default_store_8', 'Hand Tools & Measuring', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('61beec6b-69f9-9af5-8681-e06f8f2e350b', 'hardware', 'default_store_8', 'Power Tools & Machine Accessories', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('d255b57f-4c9b-5233-26fc-57aba2fd8a8c', 'hardware', 'default_store_8', 'Plumbing, Pipes & Fittings', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('df0fcb0b-040c-8f85-d3d3-a52731aa9f1c', 'hardware', 'default_store_8', 'Fasteners, Screws, Nuts & Bolts', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('0cacbd9c-9228-4f77-1da7-7fe60aa6350e', 'hardware', 'default_store_8', 'Paints, Primers & Brushes', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('a8eac1b9-0a0b-0a53-6dad-d20539b1e9b8', 'hardware', 'default_store_8', 'Adhesives, Tapes & Sealants', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('db658d2e-b3c7-4de5-f80f-630198436937', 'hardware', 'default_store_8', 'Locks, Hinges & Door Fittings', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;

-- Default categories for electrical (store: default_store_9)
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('199e3ccf-dc51-ff6d-8ec1-031b5b49c0cc', 'electrical', 'default_store_9', 'Switches, Sockets & Boards', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('4353bff4-2844-101e-b35b-e13ab4cbee91', 'electrical', 'default_store_9', 'House Wires & Power Cables', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('4cf2d220-c98f-4142-8ef8-fd159f7c1ebb', 'electrical', 'default_store_9', 'LED Bulbs, Tubes & Lighting', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('740854e1-17f3-e2e4-0b36-93910b0e623e', 'electrical', 'default_store_9', 'Ceiling Fans & Exhausts', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('a861f26f-9c81-d6b4-d0d1-cc434d1d785e', 'electrical', 'default_store_9', 'MCB, Distribution Boxes & Isolators', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('c928d13b-c4a9-3373-f38a-9cd736f10385', 'electrical', 'default_store_9', 'Extension Boards & Adapters', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('48e7af71-a57e-92ac-2e60-8e47d8a4ccec', 'electrical', 'default_store_9', 'Conduit Pipes & Fittings', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;

-- Default categories for stationery (store: default_store_10)
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('944fd7fd-2407-0ee4-c616-98dcf929ec5d', 'stationery', 'default_store_10', 'Notebooks, Registers & Diaries', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('e5f1b2dc-711f-8d59-27fe-9bcda83bff5a', 'stationery', 'default_store_10', 'Pens, Pencils & Markers', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('7b27786f-b16e-3a4f-4d2d-93732c1133ff', 'stationery', 'default_store_10', 'Office Stationery & Desk Accessories', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('a3f0392d-6cb6-d628-844a-372b205d52fb', 'stationery', 'default_store_10', 'Art, Craft & Drawing Supplies', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('61714960-e87e-3267-a916-2788145dd7df', 'stationery', 'default_store_10', 'School Supplies & Geometry Boxes', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('c724f4f8-b0ef-cfd4-4cb7-028ca993a8fb', 'stationery', 'default_store_10', 'Files, Folders & Document Bags', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('e3c2fe89-32d9-dbbc-baf5-b5f72f6b2131', 'stationery', 'default_store_10', 'Paper Reams & Photocopy Paper', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;

-- Default categories for cosmetics (store: default_store_11)
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('bee4eea1-5bca-b9b6-398c-6f2686d5aab8', 'cosmetics', 'default_store_11', 'Skin Care & Moisturizers', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('2ad782e1-9ec1-7a49-d660-1d0b39d3d62d', 'cosmetics', 'default_store_11', 'Hair Care, Shampoos & Oils', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('f845acee-fa57-5996-0e5d-6f8bdabb7426', 'cosmetics', 'default_store_11', 'Color Cosmetics & Makeup', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('1737aa06-9e7d-b07b-5fa7-291b794a02be', 'cosmetics', 'default_store_11', 'Perfumes, Deodorants & Scents', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('a9681af9-55c3-bad8-214b-af80aeb1c144', 'cosmetics', 'default_store_11', 'Oral Care & Toothpastes', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('5be033c5-cb56-ed92-8949-07c789ab34c0', 'cosmetics', 'default_store_11', 'Men''s Grooming & Shaving', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;
INSERT INTO "public"."category" (id, business_type, store_id, name, is_default, is_deleted, updated_at) VALUES ('a45bd666-85e6-a62b-20a2-4744667427da', 'cosmetics', 'default_store_11', 'Bath, Body Wash & Soaps', true, false, 1782898068322) ON CONFLICT (id) DO UPDATE SET is_default = true, name = EXCLUDED.name, updated_at = EXCLUDED.updated_at;

